-- MySQL Script generated by MySQL Workbench
-- Wed Mar  2 10:15:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema geipan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema geipan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `geipan` DEFAULT CHARACTER SET utf8mb4 ;
USE `geipan` ;

-- -----------------------------------------------------
-- Table `geipan`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geipan`.`roles` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `roleLabel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geipan`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geipan`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(255) NULL,
  `userFirstname` VARCHAR(255) NULL,
  `userMail` VARCHAR(255) NOT NULL,
  `userPassword` VARCHAR(255) NULL,
  `userAvatar` VARCHAR(255) NULL,
  `id_role` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_users_roles1_idx` (`id_role` ASC),
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`id_role`)
    REFERENCES `geipan`.`roles` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geipan`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geipan`.`states` (
  `id_state` INT NOT NULL,
  `stateNumber` VARCHAR(3) NOT NULL,
  `stateLabel` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_state`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geipan`.`observations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geipan`.`observations` (
  `id_observation` INT NOT NULL AUTO_INCREMENT,
  `obsDateTime` DATETIME NOT NULL,
  `obsDuration` TIME NULL,
  `obsLocation` VARCHAR(255) NULL,
  `obsCardinalPoint` VARCHAR(255) NULL,
  `obsWeather` VARCHAR(255) NULL,
  `obsDescription` TEXT NOT NULL,
  `id_state` INT NOT NULL,
  PRIMARY KEY (`id_observation`),
  INDEX `fk_observations_states_idx` (`id_state` ASC),
  CONSTRAINT `fk_observations_states`
    FOREIGN KEY (`id_state`)
    REFERENCES `geipan`.`states` (`id_state`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geipan`.`users_has_observations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geipan`.`users_has_observations` (
  `id_user` INT NOT NULL,
  `id_observation` INT NOT NULL,
  PRIMARY KEY (`id_user`, `id_observation`),
  INDEX `fk_users_has_observations_observations1_idx` (`id_observation` ASC),
  INDEX `fk_users_has_observations_users1_idx` (`id_user` ASC),
  CONSTRAINT `fk_users_has_observations_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `geipan`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_observations_observations1`
    FOREIGN KEY (`id_observation`)
    REFERENCES `geipan`.`observations` (`id_observation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geipan`.`observation_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geipan`.`observation_images` (
  `id_observationimage` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) NULL,
  `id_observation` INT NOT NULL,
  PRIMARY KEY (`id_observationimage`),
  INDEX `fk_observation_images_observations1_idx` (`id_observation` ASC),
  CONSTRAINT `fk_observation_images_observations1`
    FOREIGN KEY (`id_observation`)
    REFERENCES `geipan`.`observations` (`id_observation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
